apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
 - ../../base

commonLabels:
   org: Infracloud

namePrefix: stage-
replicas:
  - name: random-shapes
    count: 3
patches:
  - target:
      kind: Deployment
      name: random-shapes
    patch: |-
      - op: replace
        path: /spec/ports/nodePort
        value: 30338

