apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml

bases:
 - ../../base

commonLabels:
   org: Infracloud

namePrefix: stage-
replicas:
  - name: random-shapes
    count: 3
patches:
  - target:
      kind: Service
      name: random-shapes-svc
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30338

