apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
 - ../../base

commonLabels:
   org: Infracloud

namePrefix: stage-
replicas:
  - name: random-shapes
    count: 3
ports:
  - name: random-shapes-svc
    nodePort: 30338

#patch: |-
#        - op: replace
#          path: /spec/replicas
#          value: 2
#        - op: replace
#          path: /spec/ports/nodePort
#          value: 30338

