apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  bases:
  - ../../base

  commonLabels:
    org: Infracloud

  namePrifix: prod

  patch: |-
        - op: replace
          path: /spec/replicas
          value: 3
    
        - op: replace
          path: /spec/ports/nodePort
          value: 30339

