apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml

bases:
  - ../../base

commonLabels:
  org: Infracloud

namePrefix: prod-

replicas:
  - name: random-shapes
    count: 3

#deployment
#  patch: |-
#      - op: replace
#        path: /spec/replicas
#        value: 3
#   
#      - op: replace
#        path: /spec/ports/nodePort
#        value: 30339

