apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-shapes
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argo-notification
spec:
  selector:
    matchLabels:
      app: random-shapes
  replicas: 3
  template:
    metadata:
      labels:
        app: random-shapes
    spec:
      containers:
      - name: random-shapes
        image: ruchabhange/php-random-shapes:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: moving-shapes-colors
